nodeLinker: node-modules

# to ensure no inconsistencies we specify a Yarn version.
# when updating the version, change the path here and the two version refs in package.json
yarnPath: .yarn/releases/yarn-3.2.1.cjs
